import React from 'react'
import AboutUs from '../AboutUs/AboutUs'
import Pricing from '../Pricing/Pricing'
import Program from '../Program/Program'

export default function Home() {
  return (
    <div>
    <AboutUs/>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    
  <Pricing/>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
  <Program/>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
    <h4>hello</h4>
   
    
    
    </div>
  )
}
